### ISSUE TITLE
支持一下idea2021.3.2版本？

### ISSUE THREAD

**Issue by wangweiping** [q258523454/Java-Mybatis-SQL-Scanner#1]

**Comment by q258523454** [comment]
Plugins Marketplace：
https://plugins.jetbrains.com/plugin/18661-java-mybatis-sql-scanner

**Comment by wangweiping** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by q258523454** [comment]
> _No description provided._

本身是支持的，你这边碰到了什么问题吗？

**Comment by q258523454** [comment]
已支持!

**Comment by wangweiping** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
